USE FINAL_PROJECT;

SELECT CUSTOMER_LAST, CUSTOMER_FIRST, ORDER_DATE
from CUSTOMER  C
LEFT join ORDERS O on C.CUSTOMER_ID = O.CUSTOMER_ID;

SELECT PRODUCT_NAME, PRODUCT_TYPE, ORDER_DATE 
FROM PRODUCT P
RIGHT JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY ORDER_DATE;

SELECT PRODUCT_NAME, COUNT(ORDER_ID) AS NUMBEROFPRODUCT
FROM PRODUCT P
JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID;


SELECT COUPON_TYPE, ORDER_DATE
FROM COUPON C
JOIN ORDERS O ON C.COUPON_ID = O.COUPON_ID;

SELECT COUNT ( ORDER_ID)
FROM ORDERS;

SELECT ORDER_DATE, ORDER_ID, CUSTOMER_ID
FROM ORDERS
JOIN ORDERS.CUSTOMER_ID ON CUSTOMERS.CUSTOMER_ID
GROUP BY CUSTOMER_ID;


